server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:C:/Users/FU jiale/AppData/Local/Temp/travel_ai.db
    driver-class-name: org.sqlite.JDBC
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: travel-ai-jwt-secret-key-2024-abcdefghijklmnopqrstuvwxyz0123456789
  expire: 86400000

gaode:
  web-service-key: 3718667a98e59d3f7047d8bdb146be77
  web-js-key: b72132acac6a030e44662b3c4888535
  web-security-key: 26d05a57e53ac6fc7bac7bc209ddbe87cf7

ai:
  api-key: sk-25701b2b29a74ff087601a732288b623
  base-url: https://api.deepseek.com/v1/
  model: deepseek-chat